"""Explicit single-dispatch probe budget; no production/default timeout change."""

QUANTITATIVE_PROBE_ONCE = "QUANTITATIVE_PROBE_ONCE"
QUANTITATIVE_PROBE_REQUEST_SCOPE = "QUANTITATIVE_PROBE_ONLY"
QUANTITATIVE_PROBE_OUTPUT_TOKENS = 20_000
QUANTITATIVE_PROBE_CLIENT_TIMEOUT_SECONDS = 320
QUANTITATIVE_PROBE_MAX_CALLS = 1
